# Generated by Django 5.1.4 on 2025-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('other_category', models.CharField(blank=True, max_length=100, null=True)),
                ('speaker_name', models.CharField(max_length=100)),
                ('speaker_designation', models.CharField(max_length=100)),
                ('other_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('speaker_organization', models.CharField(max_length=200)),
                ('speaker_profile', models.TextField()),
                ('speaker_image', models.ImageField(upload_to='speaker_images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=1, max_digits=3)),
                ('meeting_platform', models.CharField(max_length=100)),
                ('other_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_link', models.URLField()),
                ('description', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('max_participants', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
