# Generated by Django 5.1.4 on 2025-01-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_chatbotknowledge_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='translations/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.topic')),
            ],
            options={
                'unique_together': {('topic', 'language')},
            },
        ),
    ]
