# Generated by Django 5.1.4 on 2025-02-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_developmentprogram_status_programday_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentprogram',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='status_program',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
