# Generated by Django 5.1.4 on 2025-02-23 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_developmentprogram_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentprogram',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='user.expert'),
        ),
    ]
