# Generated by Django 5.1.4 on 2025-03-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_programattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='program_materials/')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user.developmentprogram')),
            ],
        ),
    ]
